describe("fn-commands", function()
  it("should reset state on init", function()
    local fn = require("fn-commands")

    fn.Note(-3, 1, 3, false)

    assert.are.same(1, #fn.state.notes)

    -- Call init to reset the state
    fn.init()

    assert.are.same(0, #fn.state.notes)
  end)
  it("should always synchronize global fnState and module state", function()
    local fn = require("fn-commands")

    fn.Note(-3, 1, 3, false)

    assert.is.equal(fn.state, fnState)

    fn.init()

    assert.is.equal(fn.state, fnState)
  end)

  it("should generate the correct state for sample 102399.1", function()
    -- Load libraries
    local fn = require("fn-commands")
    local json = require("lunajson")

    -- To ensure a clean state for the test, re-initialize the module.
    -- This resets the state table.
    fn.init()

    -- Execute the sample file which uses global functions (Note, Step, etc.)
    -- to populate the fn.state table.
    dofile("./samples/102399.1.lua")

    -- Load the expected result from the pre-generated JSON file
    local expected_f = assert(io.open("./samples/102399.1.json", "r"))
    local expected_json = expected_f:read("*a")
    expected_f:close()
    local expected_table = json.decode(expected_json)

    -- Compare the state generated by the library with the expected table.
    -- assert.same performs a deep, recursive comparison of the tables.
    assert.same(expected_table, fn.state)
  end)

  it("should generate the correct chart data for sample 102399.fn14", function()
    local fn = require("fn-commands")
    local json = require("lunajson")

    local actual_table = dofile("./samples/102399.fn15.lua")

    -- modified sample data of Chart14Edit
    local expected_f = assert(io.open("./samples/102399.fn15.json", "r"))
    local expected_json = expected_f:read("*a")
    expected_f:close()
    local expected_table = json.decode(expected_json)
    expected_table.ver = fn.chartVersion

    assert.same(expected_table, actual_table)
  end)

  it("should throw error for incompatible version", function()
    local fn = require("fn-commands")

    local incompatible_chart = {
      version = "999.0",
    }

    assert.has_error(function()
      fn.chart(incompatible_chart)
    end, "fn-commands version " .. fn.version .. " cannot load chart file version " .. incompatible_chart.version)
  end)
end)
