local function removeTimeSec(tbl)
  if type(tbl) ~= "table" then
    return tbl
  end
  local copy = {}
  for k, v in pairs(tbl) do
    if k ~= "timeSec" then
      copy[k] = removeTimeSec(v)
    end
  end
  return copy
end

describe("fn-commands", function()
  it("should reset state on init", function()
    local fn = require("fn-commands")

    fn.Note(-3, 1, 3, false)

    assert.are.same(1, #fn.state.notes)

    -- Call init to reset the state
    fn.init()

    assert.are.same(0, #fn.state.notes)
    assert.are.same(0, fn.state.timeSec)
  end)

  it("should always synchronize global fnState and module state", function()
    local fn = require("fn-commands")

    fn.Note(-3, 1, 3, false)

    assert.is.equal(fn.state, fnState)

    fn.init()

    assert.is.equal(fn.state, fnState)
  end)

  it("should generate the correct state for sample 102399.1", function()
    -- Load libraries
    local fn = require("fn-commands")
    local json = require("lunajson")

    -- To ensure a clean state for the test, re-initialize the module.
    -- This resets the state table.
    fn.init()

    -- Execute the sample file which uses global functions (Note, Step, etc.)
    -- to populate the fn.state table.
    dofile("./samples/102399.1.lua")

    -- Load the expected result from the pre-generated JSON file
    local expected_f = assert(io.open("./samples/102399.1.json", "r"))
    local expected_json = expected_f:read("*a")
    expected_f:close()
    local expected_table = json.decode(expected_json)

    -- Compare the state generated by the library with the expected table.
    -- Remove timeSec fields because the fixture does not contain them.
    assert.same(expected_table, removeTimeSec(fn.state))
  end)

  it("should generate the correct chart data for sample 102399.fn17", function()
    local fn = require("fn-commands")
    local json = require("lunajson")

    local actual_table = dofile("./samples/102399.fn.lua")

    -- modified sample data of Chart14Edit
    local expected_f = assert(io.open("./samples/102399.fn17.json", "r"))
    local expected_json = expected_f:read("*a")
    expected_f:close()
    local expected_table = json.decode(expected_json)
    expected_table.ver = fn.chartVersion

    -- Remove timeSec fields because the fixture does not contain them.
    assert.same(expected_table, removeTimeSec(actual_table))
  end)

  it("should throw error for incompatible version", function()
    local fn = require("fn-commands")

    local incompatible_chart = {
      version = "999.0",
    }

    assert.has_error(function()
      fn.chart(incompatible_chart)
    end, "fn-commands version " .. fn.version .. " cannot load chart file version " .. incompatible_chart.version)
  end)

  describe("utility functions", function()
    local fn = require("fn-commands")

    it("should export stepZero", function()
      assert.same({ fourth = 0, numerator = 0, denominator = 1 }, fn.stepZero())
    end)

    it("should export stepSimplify", function()
      assert.same(
        { fourth = 1, numerator = 0, denominator = 1 },
        fn.stepSimplify({ fourth = 0, numerator = 4, denominator = 4 })
      )
      assert.same(
        { fourth = 1, numerator = 3, denominator = 4 },
        fn.stepSimplify({ fourth = 1, numerator = 6, denominator = 8 })
      )
      assert.same(
        { fourth = 0, numerator = 0, denominator = 1 },
        fn.stepSimplify({ fourth = 0, numerator = 0, denominator = 8 })
      )
      assert.same(
        { fourth = 3, numerator = 1, denominator = 2 },
        fn.stepSimplify({ fourth = 1, numerator = 5, denominator = 2 })
      )
    end)

    it("should export stepAdd", function()
      local s1 = { fourth = 1, numerator = 1, denominator = 2 }
      local s2 = { fourth = 2, numerator = 3, denominator = 4 }
      assert.same({ fourth = 4, numerator = 1, denominator = 4 }, fn.stepAdd(s1, s2))
    end)

    it("should export stepSub", function()
      local s1 = { fourth = 3, numerator = 1, denominator = 4 }
      local s2 = { fourth = 1, numerator = 1, denominator = 2 }
      assert.same({ fourth = 1, numerator = 3, denominator = 4 }, fn.stepSub(s1, s2))
    end)

    it("should export stepCmp", function()
      local s1 = { fourth = 1, numerator = 0, denominator = 1 }
      local s2 = { fourth = 0, numerator = 4, denominator = 4 }
      local s3 = { fourth = 1, numerator = 1, denominator = 4 }
      local s4 = { fourth = 0, numerator = 3, denominator = 4 }

      assert.are.equal(0, fn.stepCmp(s1, s2))
      assert.are.equal(1, fn.stepCmp(s3, s1))
      assert.are.equal(-1, fn.stepCmp(s4, s1))
    end)

    it("should export getTimeSec", function()
      local bpmChanges = {
        { bpm = 120, step = { fourth = 0, numerator = 0, denominator = 1 }, timeSec = 0 },
        { bpm = 240, step = { fourth = 4, numerator = 0, denominator = 1 }, timeSec = 2 },
      }

      assert.are.equal(0, fn.getTimeSec(bpmChanges, { fourth = 0, numerator = 0, denominator = 1 }))
      assert.are.equal(1, fn.getTimeSec(bpmChanges, { fourth = 2, numerator = 0, denominator = 1 }))
      assert.are.equal(2, fn.getTimeSec(bpmChanges, { fourth = 4, numerator = 0, denominator = 1 }))
      assert.are.equal(2.5, fn.getTimeSec(bpmChanges, { fourth = 6, numerator = 0, denominator = 1 }))

      -- with default bpm (120) when bpmChanges is empty
      assert.are.equal(2, fn.getTimeSec({}, { fourth = 4, numerator = 0, denominator = 1 }))
    end)

    it("should export getStep", function()
      local bpmChanges = {
        { bpm = 120, step = { fourth = 0, numerator = 0, denominator = 1 }, timeSec = 0 },
        { bpm = 240, step = { fourth = 4, numerator = 0, denominator = 1 }, timeSec = 2 },
      }

      assert.same({ fourth = 0, numerator = 0, denominator = 4 }, fn.getStep(bpmChanges, 0, 4))
      assert.same({ fourth = 2, numerator = 0, denominator = 4 }, fn.getStep(bpmChanges, 1, 4))
      assert.same({ fourth = 4, numerator = 0, denominator = 4 }, fn.getStep(bpmChanges, 2, 4))
      assert.same({ fourth = 6, numerator = 0, denominator = 4 }, fn.getStep(bpmChanges, 2.5, 4))
      assert.same({ fourth = 4, numerator = 2, denominator = 4 }, fn.getStep(bpmChanges, 2.125, 4))
    end)

    it("should not export utility functions to _G", function()
      assert.is_nil(_G.stepZero)
      assert.is_nil(_G.stepCmp)
      assert.is_nil(_G.stepSub)
      assert.is_nil(_G.stepAdd)
      assert.is_nil(_G.stepSimplify)
      assert.is_nil(_G.getTimeSec)
      assert.is_nil(_G.getStep)
    end)

    it("should track timeSec correctly when BPM and Step are called", function()
      fn.init()
      fn.BPM(120)
      fn.Accel(120)
      fn.Note(-1, 1, 3, false)
      assert.are.equal(0, fn.state.timeSec)
      assert.are.equal(0, fn.state.notes[1].timeSec)
      assert.are.equal(0, fn.state.bpmChanges[1].timeSec)
      assert.are.equal(0, fn.state.speedChanges[1].timeSec)

      fn.Step(4, 4) -- 4 quarter notes at 120 BPM = 2.0s
      assert.are.equal(2.0, fn.state.timeSec)

      fn.BPM(240)
      assert.are.equal(2.0, fn.state.bpmChanges[2].timeSec)

      fn.AccelEnd(240)
      assert.are.equal(2.0, fn.state.speedChanges[2].timeSec)

      fn.Step(4, 4) -- 4 quarter notes at 240 BPM = 1.0s -> total 3.0s
      fn.Note(1, 1, 3, true)
      assert.are.equal(3.0, fn.state.timeSec)
      assert.are.equal(3.0, fn.state.notes[2].timeSec)
    end)
  end)
end)
